name: .NET Build
on:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    uses: ./.github/workflows/actions/dotnet-build-test.yml
    with:
      os: ${{ matrix.os }}
